title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true

sass:
  sass_dir: _sass

plainwhite:
  name: 박선규
  tagline: student
  date_format: "%b %-d, %Y"
  sitemap: true
  search: true
  dark_mode: true
  portfolio_image: "assets/bongboo.png"
  html_lang: "en"
  condensed_mobile:
    - page
    - post
  social_links:
    twitter: samarsault
    github: sdsd6362-tech
    linkedIn: in/samarsault